export default [
  [
    {
      id: 1,
      mainImage: "./images/car-audi.png",
      model: "A1",
      mark: "Audi",
      year: "2012",
      doors: "4/5",
      ac: "Yes",
      transmission: "Manual",
      fuel: "Gasoline",
      price: "$35",
    },
  ],
  [
    {
      id: 2,
      mainImage: "./images/car-bmw.png",
      model: "X6",
      mark: "BMW",
      year: "2019",
      doors: "4/5",
      ac: "Yes",
      transmission: "Manual",
      fuel: "Disel",
      price: "$45",
    },
  ],
  [
    {
      id: 4,
      mainImage: "./images/car-golf.png",
      model: "Golf 6",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      ac: "Yes",
      transmission: "Manual",
      fuel: "Disel",
      price: "$25",
    },
  ],
  [
    {
      id: 5,
      mainImage: "./images/car-jeep.png",
      model: "Wrangler",
      mark: "Jeep",
      year: "2021",
      doors: "4/5",
      ac: "Yes",
      transmission: "Manual",
      fuel: "Disel",
      price: "$35",
    },
  ],
  [
    {
      id: 6,
      mainImage: "./images/car-mercedes.png",
      model: "Benz",
      mark: "Mercedes",
      year: "2004",
      doors: "4/5",
      ac: "No",
      transmission: "Manual",
      fuel: "Disel",
      price: "$45",
    },
  ],
];
